const contacts = [
    {
        name: "John Doe",
        img: "https://randomuser.me/api/portraits/men/1.jpg",
        tel: "123456789",
        email: "johndoe@example.com",
      },
      {
        name: "Jane Smith",
        img: "https://randomuser.me/api/portraits/women/2.jpg",
        tel: "987654321",
        email: "janesmith@example.com",
      },
      {
        name: "Michael Johnson",
        img: "https://randomuser.me/api/portraits/men/3.jpg",
        tel: "555555555",
        email: "michaeljohnson@example.com",
      },
      {
        name: "Emily Davis",
        img: "https://randomuser.me/api/portraits/women/4.jpg",
        tel: "777777777",
        email: "emilydavis@example.com",
      },
      {
        name: "David Wilson",
        img: "https://randomuser.me/api/portraits/men/5.jpg",
        tel: "333333333",
        email: "davidwilson@example.com",
      },
      {
        name: "Emma Thompson",
        img: "https://randomuser.me/api/portraits/women/6.jpg",
        tel: "999999999",
        email: "emmathompson@example.com",
      },
      {
        name: "William Harris",
        img: "https://randomuser.me/api/portraits/men/7.jpg",
        tel: "888888888",
        email: "williamharris@example.com",
      },
      {
        name: "Olivia Rodriguez",
        img: "https://randomuser.me/api/portraits/women/8.jpg",
        tel: "444444444",
        email: "oliviarodriguez@example.com",
      },
      {
        name: "James Lee",
        img: "https://randomuser.me/api/portraits/men/9.jpg",
        tel: "666666666",
        email: "jameslee@example.com",
      },
      {
        name: "Sophia Martinez",
        img: "https://randomuser.me/api/portraits/women/10.jpg",
        tel: "222222222",
        email: "sophiamartinez@example.com",
      },
      {
        name: "Benjamin Anderson",
        img: "https://randomuser.me/api/portraits/men/11.jpg",
        tel: "777777777",
        email: "benjaminanderson@example.com",
      },
      {
        name: "Isabella Taylor",
        img: "https://randomuser.me/api/portraits/women/12.jpg",
        tel: "555555555",
        email: "isabellataylor@example.com",
      },
      {
        name: "Daniel Moore",
        img: "https://randomuser.me/api/portraits/men/13.jpg",
        tel: "999999999",
        email: "danielmoore@example.com",
      },
      {
        name: "Mia Wilson",
        img: "https://randomuser.me/api/portraits/women/14.jpg",
        tel: "111111111",
        email: "miawilson@example.com",
      },
      {
        name: "Matthew Johnson",
        img: "https://randomuser.me/api/portraits/men/15.jpg",
        tel: "888888888",
        email: "matthewjohnson@example.com",
      },
      {
        name: "Sophie Davis",
        img: "https://randomuser.me/api/portraits/women/16.jpg",
        tel: "777777777",
        email: "sophiedavis@example.com",
      },
      {
        name: "Henry Wilson",
        img: "https://randomuser.me/api/portraits/men/17.jpg",
        tel: "888888888",
        email: "henrywilson@example.com",
      },
      {
        name: "Grace Thompson",
        img: "https://randomuser.me/api/portraits/women/18.jpg",
        tel: "333333333",
        email: "gracethompson@example.com",
      },
      {
        name: "Lucas Johnson",
        img: "https://randomuser.me/api/portraits/men/19.jpg",
        tel: "555555555",
        email: "lucasjohnson@example.com",
      },
      {
        name: "Chloe Smith",
        img: "https://randomuser.me/api/portraits/women/20.jpg",
        tel: "999999999",
        email: "chloesmith@example.com",
      },
      {
        name: "Noah Martinez",
        img: "https://randomuser.me/api/portraits/men/21.jpg",
        tel: "111111111",
        email: "noahmartinez@example.com",
      },
      {
        name: "Lily Harris",
        img: "https://randomuser.me/api/portraits/women/22.jpg",
        tel: "666666666",
        email: "lilyharris@example.com",
      },
      {
        name: "Elijah Rodriguez",
        img: "https://randomuser.me/api/portraits/men/23.jpg",
        tel: "444444444",
        email: "elijahrodriguez@example.com",
      },
      {
        name: "Ava Anderson",
        img: "https://randomuser.me/api/portraits/women/24.jpg",
        tel: "222222222",
        email: "avaanderson@example.com",
      },
      {
        name: "Logan Taylor",
        img: "https://randomuser.me/api/portraits/men/25.jpg",
        tel: "777777777",
        email: "logantaylor@example.com",
      },
      {
        name: "Mia Johnson",
        img: "https://randomuser.me/api/portraits/women/26.jpg",
        tel: "555555555",
        email: "miajohnson@example.com",
      },
      {
        name: "Alexander Wilson",
        img: "https://randomuser.me/api/portraits/men/27.jpg",
        tel: "999999999",
        email: "alexanderwilson@example.com",
      },
      {
        name: "Charlotte Smith",
        img: "https://randomuser.me/api/portraits/women/28.jpg",
        tel: "111111111",
        email: "charlottesmith@example.com",
      },
      {
        name: "Carter Martinez",
        img: "https://randomuser.me/api/portraits/men/29.jpg",
        tel: "888888888",
        email: "cartermartinez@example.com",
      },
      {
        name: "Scarlett Thompson",
        img: "https://randomuser.me/api/portraits/women/30.jpg",
        tel: "666666666",
        email: "scarlettthompson@example.com",
      }
]
export default contacts;